"""Manuscript typesetting kit for Auto-Research (contract ``gga-paper-v1``).

The controller ships a fixed LaTeX style (``gga-paper.sty``), a manuscript
skeleton, a controller-generated claim ledger (``claims.tex``) and a
bibliography seeded from the verified literature (``references.bib``) into the
writer's packet, then lints the submitted source and PDF against the same
contract.  The lint is deterministic and needs no TeX installation; PDF text
and font checks use poppler utilities when they are present and degrade to
byte-level checks otherwise.

Design sources the rules encode: a Times (newtx) stack with compact headings
and a running head, captions that carry caveats instead of coloured boxes in
figures, full-width figures placed before the bibliography, numbers cited only
through registered claim marks, and a ban on typewriter-font leakage of
internal identifiers into prose.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

import publication_lint

CONTRACT_ID = "gga-paper-v1"
STYLE_FILE = "gga-paper.sty"
TEMPLATE_FILE = "manuscript-template.tex"
CLAIMS_FILE = "claims.tex"
BIB_FILE = "references.bib"

# Typewriter text is for code and commands only; internal identifiers leaking
# into prose is the classic sign of an unedited machine draft.
MAX_TEXTTT_PER_1000_CHARS = 1.5
MIN_PDF_PAGES = 4
# A caption must state the reader takeaway and the encoding, not just a label.
MIN_CAPTION_CHARS = 80
# Spine entries that are front matter, not headings.
NON_HEADING_SECTIONS = {"Title", "Abstract"}
_HEADING = re.compile(r"\\(?:section|subsection|subsubsection)\*?\s*(?:\[[^\]]*\])?\s*\{((?:[^{}]|\{[^{}]*\})*)\}")
_CAPTION = re.compile(r"\\caption\s*(?:\[[^\]]*\])?\s*\{((?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*)\}", re.S)
_GGAFIGURE_CAPTION = re.compile(
    r"\\ggafigure\{[^}]*\}\{[^}]*\}\{((?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*)\}", re.S
)


def _plain(text: str) -> str:
    """Heading/caption text with LaTeX commands and braces removed, whitespace folded."""
    text = re.sub(r"\\[A-Za-z@]+\*?(?:\[[^\]]*\])?", " ", text)
    text = re.sub(r"[{}~]", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def headings(tex_text: str) -> list[str]:
    """Plain text of every \\section/\\subsection/\\subsubsection heading, comments stripped."""
    return [_plain(match.group(1)) for match in _HEADING.finditer(_strip_comments(tex_text))]


def captions(tex_text: str) -> list[str]:
    text = _strip_comments(tex_text)
    return [_plain(m.group(1)) for m in _CAPTION.finditer(text)] + [
        _plain(m.group(1)) for m in _GGAFIGURE_CAPTION.finditer(text)
    ]
TEX_PRODUCERS = re.compile(rb"pdfTeX|XeTeX|LuaTeX|LuaHBTeX|dvipdfmx|TeX Live", re.I)
TEMPLATE_FONTS = re.compile(
    r"NewTX|TeXGyreTermes|TeX Gyre Termes|Termes|Nimbus|Times|NimbusRom|CM|LM|LatinModern",
    re.I,
)

_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(text: Any) -> str:
    return "".join(_LATEX_ESCAPES.get(ch, ch) for ch in str(text))


def _format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return latex_escape(f"{value:g}" if isinstance(value, float) else str(value))
    if isinstance(value, (list, tuple)):
        return latex_escape(", ".join(f"{v:g}" if isinstance(v, float) else str(v) for v in value))
    if isinstance(value, Mapping):
        return latex_escape("; ".join(f"{k}={v}" for k, v in value.items()))
    return latex_escape(str(value))


def claims_tex(registry: Mapping[str, Any]) -> str:
    """Render every registry claim as a ``\\registerclaim`` line, sorted by id.

    Atlas claims come first (they are recomputed from the frozen outputs),
    then pilot claims (hash-bound to role artifacts).  Sorting makes the mark
    numbers deterministic for a given registry.
    """
    lines = [
        "% claims.tex -- generated by the GGA controller from research_claim_registry.json",
        "% Do not edit: the typesetting gate recomputes this file from the registry.",
        f"% contract: {CONTRACT_ID}",
    ]
    atlas = sorted(
        (item for item in registry.get("atlas_claims", []) if isinstance(item, Mapping)),
        key=lambda item: str(item.get("claim_id")),
    )
    pilot = sorted(
        (item for item in registry.get("pilot_claims", []) if isinstance(item, Mapping)),
        key=lambda item: str(item.get("claim_id")),
    )
    for group, items in (("atlas", atlas), ("pilot", pilot)):
        for item in items:
            claim_id = str(item.get("claim_id") or "").strip()
            if not claim_id:
                continue
            lines.append(
                "\\registerclaim{%s}{%s}{%s}{%s}"
                % (
                    claim_id,
                    _format_value(item.get("value")),
                    # snake_case units must be allowed to break inside the ledger column
                    latex_escape(item.get("unit") or "").replace("\\_", "\\_\\allowbreak{}"),
                    latex_escape(_source_label(item, group)),
                )
            )
    lines.append("")
    return "\n".join(lines)


def _source_label(item: Mapping[str, Any], group: str) -> str:
    """Short human-readable provenance for the ledger's source column."""
    evidence = item.get("evidence")
    if isinstance(evidence, Mapping):
        artifact = str(evidence.get("artifact") or "")
        locator = str(evidence.get("locator") or "")
        label = Path(artifact).name if artifact else f"{group} claim ledger"
        return f"{label} ({locator})" if locator else label
    for key in ("artifact", "source", "recomputed_from"):
        value = item.get(key)
        if isinstance(value, str) and value.strip():
            return Path(value).name if "/" in value else value
    return f"{group} claim ledger"


def _bib_escape(text: Any) -> str:
    return str(text).replace("{", "\\{").replace("}", "\\}")


def references_bib(citations: Sequence[Mapping[str, Any]]) -> tuple[str, list[dict[str, Any]]]:
    """Seed a BibTeX file from verified literature citations.

    Returns the bib text and the matching ``reference_list`` records (same
    keys, same order) so the writer can cite ``\\cite{lit01}`` and report the
    identical identities to the citation auditor.
    """
    entries: list[str] = [
        f"% references.bib -- seeded by the GGA controller from verified literature ({CONTRACT_ID})",
        "% Extend with additional verified references; every \\cite key must exist here.",
        "",
    ]
    records: list[dict[str, Any]] = []
    for index, item in enumerate(citations, 1):
        key = f"lit{index:02d}"
        authors = [str(a).strip() for a in (item.get("authors") or []) if str(a).strip()]
        title = str(item.get("title") or "").strip()
        year = item.get("year")
        venue = str(item.get("venue") or "").strip()
        locator = str(item.get("doi_or_official_url") or "").strip()
        doi = ""
        url = ""
        match = re.search(r"10\.\d{4,9}/[^\s\"<>]+", locator)
        if match:
            doi = match.group(0).rstrip(".")
        elif locator:
            url = locator
        fields = [
            f"  title = {{{_bib_escape(title)}}}",
            f"  author = {{{_bib_escape(' and '.join(authors))}}}",
            f"  year = {{{year}}}",
            f"  journal = {{{_bib_escape(venue)}}}",
        ]
        if doi:
            fields.append(f"  doi = {{{doi}}}")
        if url:
            fields.append(f"  url = {{{url}}}")
        entries.append(f"@article{{{key},\n" + ",\n".join(fields) + "\n}\n")
        identifier = (
            {"type": "doi", "value": doi}
            if doi
            else {"type": "official_url", "value": url or "unresolved"}
        )
        records.append(
            {
                "reference_id": key,
                "title": title,
                "authors": authors,
                "year": year,
                "venue": venue,
                "identifier": identifier,
            }
        )
    return "\n".join(entries), records


def bib_keys(bib_text: str) -> set[str]:
    return {match.group(1) for match in re.finditer(r"@\w+\s*\{\s*([^,\s]+)\s*,", bib_text)}


def _strip_comments(text: str) -> str:
    return "\n".join(re.sub(r"(?<!\\)%.*$", "", line) for line in text.splitlines())


def lint_manuscript_source(
    tex_text: str,
    *,
    bib_keys_available: Iterable[str] | None,
    registered_claim_ids: Iterable[str] | None,
    required_headings: Iterable[str] | None = None,
    declared_claim_ids: Iterable[str] | None = None,
) -> list[str]:
    """Deterministic typesetting-contract checks on the manuscript source.

    ``required_headings`` are the frozen spine sections that must exist as
    headings in the source (the writer's section manifest is not trusted on
    its own); ``declared_claim_ids`` are the claims the payload says the
    manuscript uses, each of which must actually be marked in the text.
    """
    errors: list[str] = []
    text = _strip_comments(tex_text)
    if required_headings is not None:
        present = [heading.lower() for heading in headings(tex_text)]
        missing_headings = sorted(
            name
            for name in {str(item).strip() for item in required_headings}
            if name and name not in NON_HEADING_SECTIONS
            and not any(name.lower() in heading for heading in present)
        )
        if missing_headings:
            errors.append(
                "manuscript source lacks the frozen spine headings: " + ", ".join(missing_headings[:6])
            )
    for caption in captions(tex_text):
        if len(caption) < MIN_CAPTION_CHARS:
            errors.append(
                f"figure caption {caption[:40]!r} has {len(caption)} characters; a caption states the "
                f"takeaway and the encoding (at least {MIN_CAPTION_CHARS})"
            )
            break
    if not re.search(r"\\usepackage(\[[^\]]*\])?\{gga-paper\}", text):
        errors.append("manuscript must load the controller style with \\usepackage{gga-paper}")
    if "\\input{claims}" not in text and "\\input{claims.tex}" not in text:
        errors.append("manuscript must \\input{claims} so claim marks resolve to the frozen ledger")
    if "\\printclaimledger" not in text:
        errors.append("manuscript must print the claim ledger appendix with \\printclaimledger")
    if "\\begin{abstract}" not in text:
        errors.append("manuscript lacks an abstract environment")
    if "\\maketitle" not in text:
        errors.append("manuscript lacks \\maketitle")
    if re.search(r"\\claim\{", text):
        errors.append("legacy inline \\claim{...} tags are forbidden; use \\claimref{id}")
    claim_refs = re.findall(r"\\claimref\{([^}]+)\}", text)
    if not claim_refs:
        errors.append("manuscript cites no registered claim (\\claimref) at all")
    if registered_claim_ids is not None:
        unknown = sorted({ref for ref in claim_refs if ref not in set(registered_claim_ids)})
        if unknown:
            errors.append("claim marks reference unregistered ids: " + ", ".join(unknown[:6]))
    if declared_claim_ids is not None:
        unmarked = sorted({str(item) for item in declared_claim_ids} - set(claim_refs))
        if unmarked:
            errors.append(
                "declared claim_ids never appear as \\claimref marks in the source: " + ", ".join(unmarked[:6])
            )
    texttt_count = len(re.findall(r"\\texttt\{", text))
    density = texttt_count / max(len(text) / 1000.0, 1e-9)
    if texttt_count >= 3 and density > MAX_TEXTTT_PER_1000_CHARS:
        errors.append(
            f"typewriter text appears {texttt_count} times ({density:.1f} per 1000 chars); "
            "identifiers and internal terms belong in the claim ledger, not in prose"
        )
    for match in re.finditer(r"\\includegraphics(\[[^\]]*\])?\{[^}]*\}", text):
        options = match.group(1) or ""
        if "height=" in options.replace(" ", ""):
            errors.append("figures must not fix a height; use width=\\linewidth only")
            break
        if not re.search(r"width\s*=\s*(?:[0-9.]*\s*\\(linewidth|columnwidth|textwidth))", options):
            errors.append("every \\includegraphics must set width relative to \\linewidth")
            break
    bibliography_at = min(
        [pos for pos in (text.find("\\bibliography{"), text.find("\\begin{thebibliography}")) if pos >= 0]
        or [len(text)]
    )
    figure_starts = [m.start() for m in re.finditer(r"\\begin\{figure\*?\}", text)]
    ggafigure_starts = [m.start() for m in re.finditer(r"\\ggafigure\{", text)]
    if any(pos > bibliography_at for pos in figure_starts + ggafigure_starts):
        errors.append("figures must be placed in the body before the bibliography, not appended after it")
    if not figure_starts and not ggafigure_starts:
        errors.append("manuscript embeds no figure")
    for match in re.finditer(r"\\begin\{figure\*?\}(.*?)\\end\{figure\*?\}", text, re.S):
        body = match.group(1)
        if "\\caption" not in body or "\\label" not in body:
            errors.append("every figure needs a caption and a label")
            break
    labels = set(re.findall(r"\\label\{(fig:[^}]+)\}", text))
    labels.update(re.findall(r"\\ggafigure\{(fig:[^}]+)\}", text))
    referenced = set(re.findall(r"\\(?:ref|autoref|cref|Cref|eqref)\*?\{(fig:[^}]+)\}", text))
    orphans = sorted(labels - referenced)
    if orphans:
        errors.append("figures are never referenced in the text: " + ", ".join(orphans[:4]))
    cite_keys: set[str] = set()
    for match in re.finditer(r"\\cite[tp]?\*?(?:\[[^\]]*\])*\{([^}]+)\}", text):
        cite_keys.update(key.strip() for key in match.group(1).split(",") if key.strip())
    if not cite_keys:
        errors.append("manuscript cites no reference")
    if bib_keys_available is not None:
        missing = sorted(cite_keys - set(bib_keys_available))
        if missing:
            errors.append("\\cite keys missing from the submitted bibliography: " + ", ".join(missing[:6]))
    if "\\bibliography{" not in text and "\\begin{thebibliography}" not in text:
        errors.append("manuscript must produce a bibliography (\\bibliography{references})")
    return errors


def cited_keys(tex_text: str) -> set[str]:
    """Every bib key used by a \\cite-family command, comments stripped."""
    text = _strip_comments(tex_text)
    keys: set[str] = set()
    for match in re.finditer(r"\\cite[tp]?\*?(?:\[[^\]]*\])*\{([^}]+)\}", text):
        keys.update(key.strip() for key in match.group(1).split(",") if key.strip())
    return keys


def _run(command: list[str]) -> str:
    try:
        completed = subprocess.run(command, capture_output=True, text=True, timeout=60, check=False)
    except (OSError, subprocess.SubprocessError):
        return ""
    return completed.stdout


def pdf_metadata(pdf_path: Path) -> dict[str, Any]:
    """Producer, page count, first-page text and font names with poppler when present."""
    data = pdf_path.read_bytes()
    # The Info dictionary may sit inside an object stream (pdfTeX 1.5 output),
    # so the producer probe searches the inflated object streams too.
    searchable = publication_lint.pdf_searchable_bytes(data)
    producer_fields = re.findall(
        rb"/(?:Producer|Creator|PTEX\.Fullbanner)\s*\(([^)]*)\)", searchable
    )
    meta: dict[str, Any] = {
        "producer_bytes": any(TEX_PRODUCERS.search(value) for value in producer_fields),
        "pages": publication_lint.pdf_page_count(data),
        "first_page_text": "",
        "fonts": [],
        "poppler": False,
    }
    if shutil.which("pdfinfo"):
        info = _run(["pdfinfo", str(pdf_path)])
        if info.strip():
            meta["poppler"] = True
            fields = {k.strip(): v.strip() for k, _, v in (line.partition(":") for line in info.splitlines()) if k}
            meta["producer"] = fields.get("Producer", "")
            meta["creator"] = fields.get("Creator", "")
            try:
                meta["pages"] = int(fields.get("Pages", "0") or 0)
            except ValueError:
                pass
    if shutil.which("pdftotext"):
        meta["first_page_text"] = _run(["pdftotext", "-f", "1", "-l", "1", "-layout", str(pdf_path), "-"])
    if shutil.which("pdffonts"):
        fonts = _run(["pdffonts", str(pdf_path)])
        meta["fonts"] = [line.split()[0] for line in fonts.splitlines()[2:] if line.strip()]
    return meta


def lint_manuscript_pdf(pdf_path: Path) -> list[str]:
    """Reject PDFs that were not produced by a TeX engine or that lost the front matter."""
    errors: list[str] = []
    meta = pdf_metadata(pdf_path)
    producer = f"{meta.get('producer', '')} {meta.get('creator', '')}"
    if not (TEX_PRODUCERS.search(producer.encode()) or meta["producer_bytes"]):
        errors.append(
            "manuscript PDF was not produced by a TeX engine (pdfTeX/XeTeX/LuaTeX); "
            "HTML or office renderers are not accepted"
        )
    if meta["pages"] and meta["pages"] < MIN_PDF_PAGES:
        errors.append(f"manuscript PDF has {meta['pages']} pages; a complete article needs at least {MIN_PDF_PAGES}")
    if meta["first_page_text"] and not re.search(r"\bAbstract\b", meta["first_page_text"]):
        errors.append("first PDF page shows no Abstract heading; the abstract block is missing or mis-set")
    if meta["fonts"] and not any(TEMPLATE_FONTS.search(name) for name in meta["fonts"]):
        errors.append("PDF embeds none of the template font families (NewTX/Termes/Times/CM)")
    return errors


def install_kit(destination: Path, assets_dir: Path) -> dict[str, Path]:
    """Copy the style and skeleton into a run directory; returns the written paths."""
    destination.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name in (STYLE_FILE, TEMPLATE_FILE):
        source = assets_dir / name
        target = destination / name
        target.write_bytes(source.read_bytes())
        written[name] = target
    return written
